import Head from 'next/head';
import Layout from '../components/general/Layout';
import { useRouter } from 'next/router';
import React, { useState, useEffect } from 'react';

export default function PokemonName() {
	const router = useRouter();
	const pokemonName = router.query.pokemonName;

	
	return (
		<>
			<Head>
				<title>{pokemonName}</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Layout name="Gotta catch'em all">
				<div>{pokemonName}</div>
			</Layout>
		</>
	);
}
