import Head from 'next/head';
import Layout from '../components/general/Layout';
import PokemonPageContent from '../components/pokemonPage/PokemonPageContent';
import BackButton from '../components/general/BackButton';
import axios from 'axios';
import { alternateCaps } from '../utils/utils';

export default function PokemonName({ data }) {
	const newName = alternateCaps(data.name);
	return (
		<>
			<Head>
				<title>{newName}</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Layout name={newName}>
				<BackButton />
				<PokemonPageContent pokemon={data} />
			</Layout>
		</>
	);
}

export async function getServerSideProps(context) {
	const pokemonName = context.query.pokemonName;
	const { data } = await axios(
		`https://pokeapi.co/api/v2/pokemon/${pokemonName}`
	);
	return {
		props: { data },
	};
}
