import Head from 'next/head';
import Layout from '../components/general/Layout';
import MainPageContent from '../components/mainPage/MainPageContent';

export default function Home() {
	return (
		<>
			<Head>
				<title>Pokemon test app</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Layout name="Gotta catch'em all">
        <MainPageContent/>
      </Layout>
		</>
	);
}
